export const FETCH_SEARCHED_BOOK = "FETCH_SEARCHED_BOOK"
export const FETCH_BOOK_DETAILS = "FETCH_BOOK_DETAILS"
export const DATA_LOADING = "DATA_LOADING"
export const NO_RESULT_FOUND = "NO_RESULTS_FOUND"